// ==============================================================================
// One Numan Public School (ONPS) — Android ERP Mobile Application
// Screen 15: Central In-App Push Notification Center
// Design System: Espresso Heritage Academic
// NOTE: Strictly email and in-app notifications only.

import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import '../../theme/app_theme.dart';
import '../../widgets/app_top_bar.dart';
import '../../widgets/shared_widgets.dart';

class NotificationCenterScreen extends StatefulWidget {
  const NotificationCenterScreen({super.key});

  @override
  State<NotificationCenterScreen> createState() => _NotificationCenterScreenState();
}

class _NotificationCenterScreenState extends State<NotificationCenterScreen> {
  String _selectedCategory = 'All';
  final List<String> _categories = ['All', 'Academic', 'Attendance', 'Circulars', 'Dues'];

  late List<_NotificationItem> _notifications;

  @override
  void initState() {
    super.initState();
    _notifications = [
      _NotificationItem(
        id: '1',
        title: 'Daily Attendance Recorded',
        body: 'Your child was marked PRESENT in morning roll call for their assigned class today.',
        timestamp: '10 mins ago',
        category: 'Attendance',
        isRead: false,
      ),
      _NotificationItem(
        id: '2',
        title: 'Second Assessment Examination Schedule',
        body: 'Subject date sheet for CBSE curriculum assessment has been published to your student profile.',
        timestamp: '2 hours ago',
        category: 'Academic',
        isRead: false,
      ),
      _NotificationItem(
        id: '3',
        title: 'Official School Circular Published',
        body: 'Notice regarding upcoming Winter Vacation and holiday dates has been signed by the Principal.',
        timestamp: 'Yesterday',
        category: 'Circulars',
        isRead: true,
      ),
      _NotificationItem(
        id: '4',
        title: 'Fee Ledger Summary Update',
        body: 'Official receipt REC-2026-0891 for Term 1 tuition fees has been generated by Accounts.',
        timestamp: '3 days ago',
        category: 'Dues',
        isRead: true,
      ),
      _NotificationItem(
        id: '5',
        title: 'Library Book Reminder',
        body: 'Discovery of India borrowed from Central Library is due for return in 3 calendar days.',
        timestamp: '4 days ago',
        category: 'Academic',
        isRead: true,
      ),
    ];
  }

  void _markAllAsRead() {
    setState(() {
      for (var n in _notifications) {
        n.isRead = true;
      }
    });
    ScaffoldMessenger.of(context).showSnackBar(
      const SnackBar(
        backgroundColor: AcademicColors.primary,
        content: Text('All in-app notifications marked as read.'),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final unreadCount = _notifications.where((n) => !n.isRead).length;
    final filtered = _notifications.where((n) {
      if (_selectedCategory == 'All') return true;
      return n.category == _selectedCategory;
    }).toList();

    return Scaffold(
      backgroundColor: AcademicColors.canvas,
      appBar: const AppTopBar(
        title: 'Notifications',
      ),
      body: SafeArea(
        child: Column(
          children: [
            // Category Filter Chips
            Container(
              height: 48,
              color: AcademicColors.surface,
              child: ListView.separated(
                padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 6),
                scrollDirection: Axis.horizontal,
                itemCount: _categories.length,
                separatorBuilder: (_, __) => const SizedBox(width: 8),
                itemBuilder: (context, index) {
                  final cat = _categories[index];
                  final isSelected = _selectedCategory == cat;
                  return ChoiceChip(
                    label: Text(cat),
                    selected: isSelected,
                    onSelected: (_) => setState(() => _selectedCategory = cat),
                    selectedColor: AcademicColors.primary,
                    backgroundColor: AcademicColors.canvas,
                    labelStyle: GoogleFonts.manrope(
                      fontSize: 12,
                      fontWeight: FontWeight.w600,
                      color: isSelected ? Colors.white : AcademicColors.textPrimary,
                    ),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(20),
                      side: BorderSide(color: isSelected ? AcademicColors.primary : AcademicColors.border),
                    ),
                  );
                },
              ),
            ),
            const Divider(height: 1, color: AcademicColors.border),

            if (unreadCount > 0)
              Container(
                color: AcademicColors.surface,
                padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 6),
                child: Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                    Text(
                      '$unreadCount unread notifications',
                      style: GoogleFonts.manrope(
                        fontSize: 12,
                        fontWeight: FontWeight.w600,
                        color: AcademicColors.textSecondary,
                      ),
                    ),
                    InkWell(
                      onTap: _markAllAsRead,
                      borderRadius: BorderRadius.circular(6),
                      child: Padding(
                        padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          children: [
                            const Icon(Icons.done_all, size: 14, color: AcademicColors.caramelDark),
                            const SizedBox(width: 4),
                            Text(
                              'Mark all read',
                              style: GoogleFonts.manrope(
                                fontSize: 12,
                                fontWeight: FontWeight.bold,
                                color: AcademicColors.caramelDark,
                              ),
                            ),
                          ],
                        ),
                      ),
                    ),
                  ],
                ),
              ),

            // Notifications List
            Expanded(
              child: filtered.isEmpty
                  ? Center(
                      child: Text(
                        'No notifications in $_selectedCategory',
                        style: GoogleFonts.newsreader(fontSize: 16, color: AcademicColors.textSecondary),
                      ),
                    )
                  : ListView.builder(
                      padding: const EdgeInsets.all(16),
                      itemCount: filtered.length,
                      itemBuilder: (context, index) {
                        final item = filtered[index];
                        return Padding(
                          padding: const EdgeInsets.only(bottom: 10),
                          child: InsetCard(
                            child: Row(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                Container(
                                  padding: const EdgeInsets.all(10),
                                  decoration: BoxDecoration(
                                    color: item.isRead
                                        ? AcademicColors.canvas
                                        : AcademicColors.primary.withValues(alpha: 0.1),
                                    borderRadius: BorderRadius.circular(10),
                                  ),
                                  child: Icon(
                                    _getIconForCategory(item.category),
                                    color: item.isRead ? AcademicColors.textSecondary : AcademicColors.primary,
                                    size: 20,
                                  ),
                                ),
                                const SizedBox(width: 12),
                                Expanded(
                                  child: Column(
                                    crossAxisAlignment: CrossAxisAlignment.start,
                                    children: [
                                      Row(
                                        mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                        children: [
                                          Expanded(
                                            child: Text(
                                              item.title,
                                              style: GoogleFonts.newsreader(
                                                fontSize: 15,
                                                fontWeight: FontWeight.bold,
                                                color: AcademicColors.textPrimary,
                                              ),
                                              maxLines: 1,
                                              overflow: TextOverflow.ellipsis,
                                            ),
                                          ),
                                          if (!item.isRead)
                                            Container(
                                              width: 8,
                                              height: 8,
                                              decoration: const BoxDecoration(
                                                color: AcademicColors.caramelDark,
                                                shape: BoxShape.circle,
                                              ),
                                            ),
                                        ],
                                      ),
                                      const SizedBox(height: 3),
                                      Text(
                                        item.body,
                                        style: GoogleFonts.manrope(
                                          fontSize: 12,
                                          color: AcademicColors.textPrimary,
                                          height: 1.3,
                                        ),
                                      ),
                                      const SizedBox(height: 6),
                                      Row(
                                        mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                        children: [
                                          PillBadge.secondary(item.category),
                                          Text(
                                            item.timestamp,
                                            style: GoogleFonts.manrope(
                                              fontSize: 11,
                                              color: AcademicColors.textSecondary,
                                            ),
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                ),
                              ],
                            ),
                          ),
                        );
                      },
                    ),
            ),
          ],
        ),
      ),
    );
  }

  IconData _getIconForCategory(String category) {
    switch (category) {
      case 'Attendance':
        return Icons.calendar_today_outlined;
      case 'Academic':
        return Icons.school_outlined;
      case 'Circulars':
        return Icons.campaign_outlined;
      case 'Dues':
        return Icons.receipt_long_outlined;
      default:
        return Icons.notifications_outlined;
    }
  }
}

class _NotificationItem {
  final String id;
  final String title;
  final String body;
  final String timestamp;
  final String category;
  bool isRead;

  _NotificationItem({
    required this.id,
    required this.title,
    required this.body,
    required this.timestamp,
    required this.category,
    required this.isRead,
  });
}
